// generated with lua command:
// /c helpers.write_file("defines.json", helpers.table_to_json(defines))
export const DEFINES = {
	inventory: {
		fuel: 1,
		burnt_result: 6,
		chest: 1,
		logistic_container_trash: 2,
		furnace_source: 2,
		furnace_result: 3,
		furnace_modules: 4,
		character_main: 1,
		character_guns: 3,
		character_ammo: 4,
		character_armor: 5,
		character_vehicle: 7,
		character_trash: 8,
		god_main: 2,
		editor_main: 1,
		editor_guns: 3,
		editor_ammo: 4,
		editor_armor: 5,
		roboport_robot: 1,
		roboport_material: 2,
		robot_cargo: 1,
		robot_repair: 2,
		assembling_machine_input: 2,
		assembling_machine_output: 3,
		assembling_machine_modules: 4,
		assembling_machine_dump: 7,
		lab_input: 2,
		lab_modules: 3,
		mining_drill_modules: 2,
		item_main: 1,
		rocket_silo_rocket: 9,
		rocket_silo_trash: 11,
		rocket_silo_input: 2,
		rocket_silo_output: 3,
		rocket_silo_modules: 4,
		cargo_unit: 1,
		car_trunk: 2,
		car_ammo: 3,
		cargo_wagon: 1,
		turret_ammo: 1,
		beacon_modules: 1,
		character_corpse: 1,
		artillery_turret_ammo: 1,
		artillery_wagon_ammo: 1,
		spider_trunk: 2,
		spider_ammo: 3,
		spider_trash: 4,
		hub_main: 1,
		hub_trash: 2,
		cargo_landing_pad_main: 1,
		cargo_landing_pad_trash: 2,
	},
	transport_line: {
		left_line: 1,
		right_line: 2,
		left_underground_line: 3,
		right_underground_line: 4,
		secondary_left_line: 3,
		secondary_right_line: 4,
		left_split_line: 5,
		right_split_line: 6,
		secondary_left_split_line: 7,
		secondary_right_split_line: 8,
	},
	direction: {
		north: 0,
		northnortheast: 1,
		northeast: 2,
		eastnortheast: 3,
		east: 4,
		eastsoutheast: 5,
		southeast: 6,
		southsoutheast: 7,
		south: 8,
		southsouthwest: 9,
		southwest: 10,
		westsouthwest: 11,
		west: 12,
		westnorthwest: 13,
		northwest: 14,
		northnorthwest: 15,
	},
	riding: {
		acceleration: {
			nothing: 0,
			accelerating: 1,
			braking: 2,
			reversing: 3,
		},
		direction: { left: 0, straight: 1, right: 2 },
	},
	shooting: {
		not_shooting: 0,
		shooting_enemies: 1,
		shooting_selected: 2,
	},
	command: {
		attack: 1,
		go_to_location: 2,
		compound: 3,
		group: 4,
		attack_area: 5,
		wander: 6,
		flee: 8,
		stop: 9,
		build_base: 7,
	},
	distraction: { none: 0, by_enemy: 1, by_anything: 3, by_damage: 4 },
	compound_command: { logical_and: 0, logical_or: 1, return_last: 2 },
	difficulty: { easy: 0, normal: 1, hard: 2 },
	events: {
		on_pre_scenario_finished: 198,
		on_research_moved: 197,
		on_player_locale_changed: 196,
		on_achievement_gained: 195,
		on_player_input_method_changed: 194,
		on_cutscene_finished: 193,
		on_cutscene_started: 192,
		on_entity_color_changed: 191,
		on_gui_leave: 190,
		on_gui_hover: 189,
		on_player_alt_reverse_selected_area: 188,
		on_player_reverse_selected_area: 187,
		on_space_platform_changed_state: 186,
		on_equipment_removed: 185,
		on_equipment_inserted: 184,
		on_redo_applied: 183,
		on_undo_applied: 182,
		on_entity_logistic_slot_changed: 181,
		on_spider_command_completed: 180,
		on_player_used_spidertron_remote: 179,
		on_cutscene_cancelled: 178,
		on_permission_group_added: 177,
		on_permission_group_deleted: 176,
		on_pre_permission_group_deleted: 175,
		on_permission_string_imported: 174,
		on_pre_permission_string_imported: 173,
		on_permission_group_edited: 172,
		on_player_flushed_fluid: 171,
		on_player_clicked_gps_tag: 170,
		on_object_destroyed: 169,
		on_script_inventory_resized: 168,
		on_pre_script_inventory_resized: 167,
		on_pre_player_toggled_map_editor: 166,
		on_player_set_quick_bar_slot: 165,
		on_script_trigger_effect: 164,
		on_string_translated: 163,
		on_force_cease_fire_changed: 162,
		on_force_friends_changed: 161,
		on_gui_switch_state_changed: 160,
		on_gui_selected_tab_changed: 159,
		on_gui_location_changed: 158,
		on_gui_confirmed: 157,
		on_chart_tag_removed: 156,
		on_chart_tag_modified: 155,
		on_chart_tag_added: 154,
		on_trigger_fired_artillery: 153,
		on_build_base_arrived: 152,
		on_unit_group_finished_gathering: 151,
		on_unit_removed_from_group: 150,
		on_unit_added_to_group: 149,
		on_unit_group_created: 148,
		on_pre_player_removed: 147,
		on_segment_entity_created: 146,
		on_entity_spawned: 145,
		on_post_entity_died: 144,
		on_robot_exploded_cliff: 143,
		on_pre_robot_exploded_cliff: 142,
		on_pre_chunk_deleted: 141,
		on_player_fast_transferred: 140,
		on_player_repaired_entity: 139,
		on_player_toggled_alt_mode: 138,
		on_surface_renamed: 137,
		on_surface_imported: 136,
		on_game_created_from_scenario: 135,
		on_brush_cloned: 134,
		on_area_cloned: 133,
		on_entity_cloned: 132,
		on_player_toggled_map_editor: 131,
		on_cancelled_upgrade: 130,
		on_marked_for_upgrade: 129,
		on_ai_command_completed: 128,
		on_script_path_request_finished: 127,
		on_rocket_launch_ordered: 126,
		on_player_unbanned: 125,
		on_player_kicked: 124,
		on_player_banned: 123,
		on_train_schedule_changed: 122,
		on_chunk_deleted: 121,
		on_pre_surface_cleared: 120,
		on_surface_cleared: 119,
		on_pre_player_left_game: 118,
		on_player_trash_inventory_changed: 117,
		on_forces_merged: 116,
		on_land_mine_armed: 115,
		on_force_reset: 114,
		on_technology_effects_reset: 113,
		on_chunk_charted: 112,
		on_entity_damaged: 111,
		on_player_cancelled_crafting: 110,
		on_pre_player_crafted_item: 109,
		on_player_display_density_scale_changed: 108,
		on_player_display_scale_changed: 107,
		on_player_display_resolution_changed: 106,
		on_player_pipette: 105,
		on_pre_ghost_upgraded: 104,
		on_pre_ghost_deconstructed: 103,
		on_character_corpse_expired: 102,
		on_player_cheat_mode_disabled: 101,
		on_player_cheat_mode_enabled: 100,
		on_player_unmuted: 99,
		on_player_muted: 98,
		on_gui_value_changed: 97,
		on_gui_closed: 96,
		on_gui_opened: 95,
		on_mod_item_opened: 94,
		on_player_changed_position: 93,
		on_worker_robot_expired: 92,
		on_combat_robot_expired: 91,
		script_raised_set_tiles: 90,
		script_raised_teleported: 89,
		script_raised_revive: 88,
		script_raised_destroy: 87,
		script_raised_built: 86,
		on_player_demoted: 85,
		on_player_promoted: 84,
		on_player_used_capsule: 83,
		on_player_removed: 82,
		on_console_command: 81,
		on_console_chat: 80,
		on_player_configured_blueprint: 79,
		on_player_deconstructed_area: 78,
		on_player_setup_blueprint: 77,
		on_gui_elem_changed: 76,
		on_train_created: 75,
		on_space_platform_mined_tile: 74,
		on_space_platform_built_tile: 73,
		on_space_platform_built_entity: 72,
		on_space_platform_mined_item: 71,
		on_space_platform_pre_mined: 70,
		on_space_platform_mined_entity: 69,
		on_player_mined_entity: 68,
		on_robot_mined_entity: 67,
		on_pre_surface_deleted: 66,
		on_surface_deleted: 65,
		on_surface_created: 64,
		on_runtime_mod_setting_changed: 63,
		on_gui_selection_state_changed: 62,
		on_entity_renamed: 61,
		on_player_changed_force: 60,
		on_biter_base_built: 59,
		on_player_dropped_item: 58,
		on_market_item_purchased: 57,
		on_selected_entity_changed: 56,
		on_player_controller_changed: 55,
		on_player_changed_surface: 54,
		on_player_alt_selected_area: 53,
		on_player_selected_area: 52,
		on_robot_mined_tile: 51,
		on_robot_built_tile: 50,
		on_player_mined_tile: 49,
		on_player_built_tile: 48,
		on_player_left_game: 47,
		on_player_joined_game: 46,
		on_player_respawned: 45,
		on_player_died: 44,
		on_pre_player_died: 43,
		on_player_removed_equipment: 42,
		on_player_placed_equipment: 41,
		on_player_gun_inventory_changed: 40,
		on_player_ammo_inventory_changed: 39,
		on_player_armor_inventory_changed: 38,
		on_lua_shortcut: 37,
		on_cutscene_waypoint_reached: 36,
		on_player_main_inventory_changed: 35,
		on_entity_settings_pasted: 34,
		on_pre_entity_settings_pasted: 33,
		on_player_cursor_stack_changed: 32,
		on_forces_merging: 31,
		on_force_created: 30,
		on_player_driving_changed_state: 29,
		on_resource_depleted: 28,
		on_player_created: 27,
		on_train_changed_state: 26,
		on_trigger_created_entity: 25,
		on_cancelled_deconstruction: 24,
		on_marked_for_deconstruction: 23,
		on_player_flipped_entity: 22,
		on_player_rotated_entity: 21,
		on_research_cancelled: 20,
		on_research_reversed: 19,
		on_research_finished: 18,
		on_research_started: 17,
		on_robot_mined: 16,
		on_robot_pre_mined: 15,
		on_robot_built_entity: 14,
		on_player_crafted_item: 13,
		on_chunk_generated: 12,
		on_pre_player_mined_item: 11,
		on_rocket_launched: 10,
		on_pre_build: 9,
		on_player_mined_item: 8,
		on_sector_scanned: 7,
		on_built_entity: 6,
		on_picked_up_item: 5,
		on_entity_died: 4,
		on_gui_checked_state_changed: 3,
		on_gui_text_changed: 2,
		on_gui_click: 1,
		on_tick: 0,
	},
	controllers: {
		ghost: 0,
		character: 1,
		god: 2,
		editor: 4,
		cutscene: 6,
		spectator: 5,
		remote: 7,
	},
	group_state: {
		gathering: 0,
		moving: 1,
		attacking_distraction: 2,
		attacking_target: 3,
		finished: 4,
		pathfinding: 5,
		wander_in_group: 6,
	},
	wire_type: { red: 2, green: 3, copper: 1 },
	wire_connector_id: {
		circuit_red: 1,
		circuit_green: 2,
		combinator_input_red: 1,
		combinator_input_green: 2,
		combinator_output_red: 3,
		combinator_output_green: 4,
		pole_copper: 5,
		power_switch_left_copper: 5,
		power_switch_right_copper: 6,
	},
	wire_origin: { player: 1, script: 2, radars: 3 },
	train_state: {
		on_the_path: 0,
		no_schedule: 1,
		no_path: 2,
		arrive_signal: 3,
		wait_signal: 4,
		arrive_station: 5,
		manual_control_stop: 7,
		manual_control: 8,
		wait_station: 6,
		destination_full: 9,
	},
	space_platform_state: {
		waiting_for_starter_pack: 0,
		starter_pack_requested: 8,
		starter_pack_on_the_way: 1,
		on_the_path: 2,
		waiting_for_departure: 3,
		no_schedule: 4,
		no_path: 5,
		waiting_at_station: 6,
		paused: 7,
	},
	signal_state: {
		open: 0,
		closed: 1,
		reserved: 2,
		reserved_by_circuit_network: 3,
	},
	chain_signal_state: {
		none: 0,
		all_open: 1,
		partially_open: 2,
		none_open: 3,
	},
	rail_direction: { front: 0, back: 1 },
	rail_connection_direction: {
		left: 0,
		straight: 1,
		right: 2,
		none: 3,
	},
	control_behavior: {
		inserter: { hand_read_mode: { hold: 1, pulse: 0 } },
		logistic_container: {
			exclusive_mode: { send_contents: 0, set_requests: 1, none: 2 },
		},
		lamp: {
			color_mode: { color_mapping: 0, components: 1, packed_rgb: 2 },
		},
		mining_drill: {
			resource_read_mode: { this_miner: 0, entire_patch: 1 },
		},
		transport_belt: {
			content_read_mode: { pulse: 0, hold: 1, entire_belt_hold: 2 },
		},
		rocket_silo: {
			read_mode: { none: 0, logistic_inventory: 1, orbital_requests: 2 },
		},
		roboport: {
			read_items_mode: { none: 0, logistics: 1, missing_requests: 2 },
		},
		cargo_landing_pad: {
			exclusive_mode: { none: 2, send_contents: 0, set_requests: 1 },
		},
		type: {
			container: 1,
			generic_on_off: 2,
			inserter: 3,
			lamp: 4,
			logistic_container: 5,
			roboport: 6,
			storage_tank: 7,
			train_stop: 8,
			decider_combinator: 9,
			arithmetic_combinator: 10,
			constant_combinator: 11,
			transport_belt: 12,
			accumulator: 13,
			rail_signal: 14,
			rail_chain_signal: 18,
			wall: 15,
			mining_drill: 16,
			programmable_speaker: 17,
			assembling_machine: 19,
			pump: 21,
			selector_combinator: 20,
			rocket_silo: 22,
			turret: 23,
			reactor: 24,
			space_platform_hub: 25,
			artillery_turret: 26,
			asteroid_collector: 28,
			radar: 27,
			display_panel: 29,
			loader: 30,
			cargo_landing_pad: 31,
			agricultural_tower: 32,
		},
	},
	chunk_generated_status: {
		nothing: 0,
		custom_tiles: 10,
		basic_tiles: 20,
		corrected_tiles: 30,
		tiles: 40,
		entities: 50,
	},
	logistic_mode: {
		none: 0,
		active_provider: 1,
		storage: 2,
		requester: 3,
		passive_provider: 4,
		buffer: 5,
	},
	logistic_member_index: {
		logistic_container: 0,
		vehicle_storage: 1,
		character_requester: 0,
		character_storage: 1,
		character_provider: 2,
		generic_on_off_behavior: 0,
		spidertron_requester: 0,
	},
	deconstruction_item: {
		entity_filter_mode: { whitelist: 0, blacklist: 1 },
		tile_filter_mode: { whitelist: 0, blacklist: 1 },
		tile_selection_mode: { normal: 0, always: 1, never: 2, only: 3 },
	},
	alert_type: {
		entity_destroyed: 0,
		entity_under_attack: 1,
		not_enough_construction_robots: 2,
		no_material_for_construction: 3,
		not_enough_repair_packs: 4,
		platform_tile_building_blocked: 5,
		turret_out_of_ammo: 6,
		turret_fire: 7,
		custom: 8,
		no_storage: 9,
		train_out_of_fuel: 10,
		train_no_path: 11,
		no_platform_storage: 12,
		collector_path_blocked: 13,
		unclaimed_cargo: 14,
		no_roboport_storage: 15,
		pipeline_overextended: 16,
	},
	mouse_button_type: { none: 1, left: 2, right: 4, middle: 8 },
	input_action: {
		activate_interrupt: 176,
		activate_paste: 42,
		add_decider_combinator_condition: 157,
		add_decider_combinator_output: 161,
		add_logistic_section: 53,
		add_permission_group: 272,
		add_pin: 305,
		add_train_interrupt: 175,
		add_train_station: 174,
		adjust_blueprint_snapping: 316,
		admin_action: 229,
		alt_reverse_select_area: 196,
		alt_select_area: 194,
		alt_select_blueprint_entities: 129,
		alternative_copy: 127,
		begin_mining: 2,
		begin_mining_terrain: 67,
		build: 65,
		build_rail: 190,
		build_terrain: 169,
		cancel_craft: 89,
		cancel_deconstruct: 153,
		cancel_delete_space_platform: 234,
		cancel_new_blueprint: 15,
		cancel_research: 191,
		cancel_upgrade: 154,
		change_active_character_tab: 107,
		change_active_item_group_for_crafting: 105,
		change_active_item_group_for_filters: 106,
		change_active_quick_bar: 277,
		change_arithmetic_combinator_parameters: 155,
		change_entity_label: 184,
		change_item_label: 183,
		change_logistic_point_group: 186,
		change_multiplayer_config: 228,
		change_picking_state: 241,
		change_programmable_speaker_alert_parameters: 166,
		change_programmable_speaker_circuit_parameters: 167,
		change_programmable_speaker_parameters: 165,
		change_riding_state: 68,
		change_selector_combinator_parameters: 164,
		change_shooting_state: 83,
		change_train_name: 185,
		change_train_stop_station: 104,
		change_train_wait_condition: 170,
		change_train_wait_condition_data: 171,
		clear_cursor: 11,
		connect_rolling_stock: 8,
		copy: 126,
		copy_entity_settings: 17,
		copy_large_opened_blueprint: 133,
		copy_large_opened_item: 21,
		copy_opened_blueprint: 132,
		copy_opened_item: 20,
		craft: 81,
		create_space_platform: 232,
		cursor_split: 75,
		cursor_transfer: 74,
		custom_input: 182,
		cycle_blueprint_book_backwards: 29,
		cycle_blueprint_book_forwards: 28,
		cycle_quality_down: 31,
		cycle_quality_up: 30,
		deconstruct: 124,
		delete_blueprint_library: 40,
		delete_blueprint_record: 138,
		delete_custom_tag: 270,
		delete_logistic_group: 188,
		delete_permission_group: 271,
		delete_space_platform: 233,
		destroy_item: 71,
		destroy_opened_item: 19,
		disconnect_rolling_stock: 9,
		drag_decider_combinator_condition: 156,
		drag_decider_combinator_output: 160,
		drag_train_schedule: 210,
		drag_train_schedule_interrupt: 211,
		drag_train_wait_condition: 212,
		drop_blueprint_record: 137,
		drop_item: 64,
		edit_blueprint_tool_preview: 146,
		edit_custom_tag: 202,
		edit_display_panel: 298,
		edit_display_panel_always_show: 299,
		edit_display_panel_icon: 301,
		edit_display_panel_parameters: 302,
		edit_display_panel_show_in_chart: 300,
		edit_interrupt: 177,
		edit_permission_group: 203,
		edit_pin: 309,
		enable_transitional_requests: 276,
		export_blueprint: 148,
		fast_entity_split: 258,
		fast_entity_transfer: 255,
		flip_entity: 257,
		flush_opened_entity_fluid: 51,
		flush_opened_entity_specific_fluid: 240,
		go_to_train_station: 179,
		grab_blueprint_record: 136,
		gui_checked_state_changed: 109,
		gui_click: 100,
		gui_confirmed: 101,
		gui_elem_changed: 208,
		gui_hover: 312,
		gui_leave: 313,
		gui_location_changed: 114,
		gui_selected_tab_changed: 111,
		gui_selection_state_changed: 110,
		gui_switch_state_changed: 113,
		gui_text_changed: 108,
		gui_value_changed: 112,
		import_blueprint: 149,
		import_blueprint_string: 204,
		import_blueprints_filtered: 150,
		import_permissions_string: 205,
		instantly_create_space_platform: 239,
		inventory_split: 88,
		inventory_transfer: 79,
		land_at_planet: 319,
		launch_rocket: 187,
		lua_shortcut: 230,
		map_editor_action: 225,
		market_offer: 103,
		mod_settings_changed: 200,
		modify_decider_combinator_condition: 158,
		modify_decider_combinator_output: 162,
		move_research: 192,
		open_achievements_gui: 27,
		open_blueprint_library_gui: 62,
		open_blueprint_record: 135,
		open_bonus_gui: 26,
		open_character_gui: 6,
		open_current_vehicle_gui: 7,
		open_equipment: 73,
		open_global_electric_network_gui: 294,
		open_gui: 5,
		open_item: 69,
		open_logistics_gui: 61,
		open_mod_item: 72,
		open_new_platform_button_from_rocket_silo: 58,
		open_opened_entity_grid: 55,
		open_parent_of_opened_item: 70,
		open_production_gui: 13,
		open_train_gui: 264,
		open_train_station_gui: 284,
		open_trains_gui: 265,
		parametrise_blueprint: 321,
		paste_entity_settings: 18,
		pin_alert_group: 307,
		pin_custom_alert: 308,
		pin_search_result: 306,
		pipette: 86,
		place_equipment: 115,
		quick_bar_pick_slot: 222,
		quick_bar_set_selected_page: 223,
		quick_bar_set_slot: 221,
		reassign_blueprint: 134,
		redo: 44,
		remote_view_entity: 237,
		remote_view_surface: 236,
		remove_cables: 147,
		remove_decider_combinator_condition: 159,
		remove_decider_combinator_output: 163,
		remove_logistic_section: 297,
		remove_pin: 310,
		remove_train_interrupt: 173,
		remove_train_station: 172,
		rename_interrupt: 178,
		rename_space_platform: 235,
		reorder_logistic_section: 303,
		request_missing_construction_materials: 259,
		reset_assembling_machine: 12,
		reverse_select_area: 195,
		rotate_entity: 256,
		select_area: 193,
		select_asteroid_chunk_slot: 216,
		select_blueprint_entities: 128,
		select_entity_filter_slot: 215,
		select_entity_slot: 214,
		select_item_filter: 213,
		select_mapper_slot_from: 218,
		select_mapper_slot_to: 219,
		select_next_valid_gun: 38,
		select_tile_slot: 217,
		send_spidertron: 118,
		send_stack_to_trash: 77,
		send_stacks_to_trash: 78,
		send_train_to_pin_target: 311,
		set_behavior_mode: 254,
		set_car_weapons_control: 274,
		set_cheat_mode_quality: 96,
		set_circuit_condition: 93,
		set_circuit_mode_of_operation: 99,
		set_combinator_description: 246,
		set_copy_color_from_train_stop: 267,
		set_deconstruction_item_tile_selection_mode: 269,
		set_deconstruction_item_trees_and_rocks_only: 268,
		set_entity_color: 266,
		set_entity_energy_property: 201,
		set_filter: 90,
		set_ghost_cursor: 142,
		set_heat_interface_mode: 283,
		set_heat_interface_temperature: 282,
		set_infinity_container_filter_item: 198,
		set_infinity_container_remove_unfiltered_items: 273,
		set_infinity_pipe_filter: 199,
		set_inserter_max_stack_size: 263,
		set_inventory_bar: 119,
		set_lamp_always_on: 293,
		set_linked_container_link_i_d: 291,
		set_logistic_filter_item: 97,
		set_logistic_network_name: 189,
		set_logistic_section_active: 304,
		set_player_color: 287,
		set_pump_fluid_filter: 295,
		set_request_from_buffers: 275,
		set_research_finished_stops_game: 262,
		set_rocket_silo_send_to_orbit_automated_mode: 323,
		set_schedule_record_allow_unloading: 181,
		set_signal: 94,
		set_splitter_priority: 280,
		set_spoil_priority: 91,
		set_train_stop_priority: 317,
		set_train_stopped: 180,
		set_trains_limit: 289,
		set_turret_ignore_unlisted: 292,
		set_use_inserter_filters: 250,
		set_vehicle_automatic_targeting_parameters: 168,
		setup_assembling_machine: 84,
		setup_blueprint: 130,
		setup_single_blueprint_record: 131,
		spawn_item: 141,
		spectator_change_surface: 315,
		stack_split: 87,
		stack_transfer: 76,
		start_repair: 123,
		start_research: 95,
		start_walking: 66,
		stop_drag_build: 50,
		swap_logistic_filter_items: 98,
		switch_connect_to_logistic_network: 253,
		switch_constant_combinator_state: 247,
		switch_inserter_filter_mode_state: 249,
		switch_loader_filter_mode: 251,
		switch_mining_drill_filter_mode_state: 252,
		switch_power_switch_state: 248,
		take_equipment: 116,
		toggle_artillery_auto_targeting: 49,
		toggle_deconstruction_item_entity_filter_mode: 36,
		toggle_deconstruction_item_tile_filter_mode: 37,
		toggle_driving: 4,
		toggle_enable_vehicle_logistics_while_moving: 35,
		toggle_entity_logistic_requests: 48,
		toggle_equipment_movement_bonus: 46,
		toggle_map_editor: 39,
		toggle_personal_logistic_requests: 47,
		toggle_personal_roboport: 45,
		toggle_selected_entity: 59,
		toggle_show_entity_info: 22,
		translate_string: 231,
		trash_not_requested_items: 260,
		undo: 43,
		upgrade: 125,
		upgrade_opened_blueprint_by_item: 140,
		upgrade_opened_blueprint_by_record: 139,
		use_item: 117,
		wire_dragging: 82,
		write_to_console: 102,
	},
	build_check_type: {
		script: 0,
		manual: 1,
		manual_ghost: 3,
		script_ghost: 2,
		blueprint_ghost: 4,
		ghost_revive: 5,
	},
	gui_type: {
		none: 0,
		entity: 1,
		controller: 3,
		production: 4,
		item: 5,
		bonus: 6,
		trains: 7,
		achievement: 8,
		blueprint_library: 9,
		equipment: 10,
		logistic: 11,
		other_player: 12,
		permissions: 14,
		custom: 16,
		server_management: 17,
		player_management: 18,
		tile: 19,
		global_electric_network: 22,
		script_inventory: 23,
		opened_entity_grid: 24,
	},
	behavior_result: {
		in_progress: 0,
		fail: 1,
		success: 2,
		deleted: 3,
	},
	flow_precision_index: {
		five_seconds: 0,
		one_minute: 1,
		ten_minutes: 2,
		one_hour: 3,
		ten_hours: 4,
		fifty_hours: 5,
		two_hundred_fifty_hours: 6,
		one_thousand_hours: 7,
	},
	entity_status: {
		working: 1,
		normal: 2,
		ghost: 3,
		broken: 4,
		no_power: 54,
		low_power: 14,
		no_fuel: 53,
		frozen: 58,
		disabled_by_control_behavior: 55,
		opened_by_circuit_network: 57,
		closed_by_circuit_network: 56,
		disabled_by_script: 60,
		marked_for_deconstruction: 62,
		paused: 59,
		not_plugged_in_electric_network: 5,
		networks_connected: 6,
		networks_disconnected: 7,
		charging: 8,
		discharging: 9,
		fully_charged: 10,
		out_of_logistic_network: 15,
		no_recipe: 19,
		no_ingredients: 18,
		no_input_fluid: 24,
		no_research_in_progress: 20,
		no_minable_resources: 21,
		not_connected_to_hub_or_pad: 22,
		low_input_fluid: 23,
		fluid_ingredient_shortage: 25,
		full_output: 27,
		not_enough_space_in_output: 28,
		full_burnt_result_output: 29,
		item_ingredient_shortage: 26,
		missing_required_fluid: 30,
		missing_science_packs: 31,
		waiting_for_source_items: 32,
		waiting_for_more_items: 33,
		waiting_for_space_in_destination: 34,
		preparing_rocket_for_launch: 35,
		waiting_to_launch_rocket: 36,
		waiting_for_space_in_platform_hub: 37,
		launching_rocket: 38,
		thrust_not_required: 39,
		on_the_way: 40,
		waiting_in_orbit: 41,
		waiting_at_stop: 42,
		waiting_for_rockets_to_arrive: 43,
		not_enough_thrust: 44,
		destination_stop_full: 45,
		no_path: 46,
		no_modules_to_transmit: 47,
		recharging_after_power_outage: 48,
		waiting_for_target_to_be_built: 49,
		waiting_for_train: 50,
		no_ammo: 51,
		low_temperature: 52,
		disabled: 61,
		turned_off_during_daytime: 11,
		not_connected_to_rail: 13,
		cant_divide_segments: 12,
		no_filter: 64,
		no_spot_seedable_by_inputs: 17,
		waiting_for_plants_to_grow: 16,
		computing_navigation: 63,
		pipeline_overextended: 65,
		recipe_not_researched: 66,
	},
	entity_status_diode: { green: 0, red: 1, yellow: 2 },
	rocket_silo_status: {
		building_rocket: 0,
		create_rocket: 1,
		lights_blinking_open: 2,
		doors_opening: 3,
		doors_opened: 4,
		rocket_rising: 5,
		arms_advance: 6,
		rocket_ready: 7,
		launch_starting: 8,
		engine_starting: 9,
		arms_retract: 10,
		rocket_flying: 11,
		lights_blinking_close: 12,
		doors_closing: 13,
		launch_started: 14,
	},
	render_mode: { game: 1, chart: 2, chart_zoomed_in: 3 },
	input_method: { keyboard_and_mouse: 0, game_controller: 1 },
	game_controller_interaction: { always: 0, never: 2, normal: 1 },
	rich_text_setting: { enabled: 17, disabled: 0, highlight: 30 },
	relative_gui_position: { top: 0, bottom: 1, left: 2, right: 3 },
	relative_gui_type: {
		script_inventory_gui: 'script-inventory-gui',
		cargo_landing_pad_gui: 'cargo-landing-pad-gui',
		space_platform_hub_gui: 'space-platform-hub-gui',
		tile_variations_gui: 'tile-variations-gui',
		ghost_picker_gui: 'ghost-picker-gui',
		resource_entity_gui: 'resource-entity-gui',
		blueprint_library_gui: 'blueprint-library-gui',
		market_gui: 'market-gui',
		power_switch_gui: 'power-switch-gui',
		global_electric_network_gui: 'global-electric-network-gui',
		generic_on_off_entity_gui: 'generic-on-off-entity-gui',
		infinity_pipe_gui: 'infinity-pipe-gui',
		loader_gui: 'loader-gui',
		agriculture_tower_gui: 'agriculture-tower-gui',
		blueprint_setup_gui: 'blueprint-setup-gui',
		accumulator_gui: 'accumulator-gui',
		deconstruction_item_gui: 'deconstruction-item-gui',
		rocket_silo_gui: 'rocket-silo-gui',
		equipment_grid_gui: 'equipment-grid-gui',
		electric_energy_interface_gui: 'electric-energy-interface-gui',
		entity_variations_gui: 'entity-variations-gui',
		production_gui: 'production-gui',
		item_with_inventory_gui: 'item-with-inventory-gui',
		bonus_gui: 'bonus-gui',
		pick_stop_gui: 'pick-stop-gui',
		asteroid_collector_gui: 'asteroid-collector-gui',
		splitter_gui: 'splitter-gui',
		admin_gui: 'admin-gui',
		inserter_gui: 'inserter-gui',
		burner_equipment_gui: 'burner-equipment-gui',
		pipe_gui: 'pipe-gui',
		lamp_gui: 'lamp-gui',
		permissions_gui: 'permissions-gui',
		logistic_gui: 'logistic-gui',
		rail_signal_base_gui: 'rail-signal-base-gui',
		train_gui: 'train-gui',
		storage_tank_gui: 'storage-tank-gui',
		wall_gui: 'wall-gui',
		turret_gui: 'turret-gui',
		achievement_gui: 'achievement-gui',
		entity_with_energy_source_gui: 'entity-with-energy-source-gui',
		additional_entity_info_gui: 'additional-entity-info-gui',
		spider_vehicle_gui: 'spider-vehicle-gui',
		upgrade_item_gui: 'upgrade-item-gui',
		display_panel_gui: 'display-panel-gui',
		controller_gui: 'controller-gui',
		server_config_gui: 'server-config-gui',
		armor_gui: 'armor-gui',
		other_player_gui: 'other-player-gui',
		decider_combinator_gui: 'decider-combinator-gui',
		tips_and_tricks_gui: 'tips-and-tricks-gui',
		blueprint_book_gui: 'blueprint-book-gui',
		container_gui: 'container-gui',
		programmable_speaker_gui: 'programmable-speaker-gui',
		transport_belt_gui: 'transport-belt-gui',
		car_gui: 'car-gui',
		pump_gui: 'pump-gui',
		reactor_gui: 'reactor-gui',
		mining_drill_gui: 'mining-drill-gui',
		linked_container_gui: 'linked-container-gui',
		assembling_machine_select_recipe_gui: 'assembling-machine-select-recipe-gui',
		assembling_machine_gui: 'assembling-machine-gui',
		furnace_gui: 'furnace-gui',
		lab_gui: 'lab-gui',
		roboport_gui: 'roboport-gui',
		train_stop_gui: 'train-stop-gui',
		heat_interface_gui: 'heat-interface-gui',
		electric_network_gui: 'electric-network-gui',
		beacon_gui: 'beacon-gui',
		arithmetic_combinator_gui: 'arithmetic-combinator-gui',
		selector_combinator_gui: 'selector-combinator-gui',
		trains_gui: 'trains-gui',
		constant_combinator_gui: 'constant-combinator-gui',
		standalone_character_gui: 'standalone-character-gui',
	},
	disconnect_reason: {
		quit: 0,
		dropped: 1,
		reconnect: 2,
		wrong_input: 3,
		desync_limit_reached: 4,
		cannot_keep_up: 5,
		afk: 6,
		kicked: 7,
		kicked_and_deleted: 8,
		banned: 9,
		switching_servers: 11,
	},
	prototypes: {
		achievement: {
			achievement: 0,
			'build-entity-achievement': 0,
			'change-surface-achievement': 0,
			'combat-robot-count-achievement': 0,
			'complete-objective-achievement': 0,
			'construct-with-robots-achievement': 0,
			'create-platform-achievement': 0,
			'deconstruct-with-robots-achievement': 0,
			'deliver-by-robots-achievement': 0,
			'deplete-resource-achievement': 0,
			'destroy-cliff-achievement': 0,
			'dont-build-entity-achievement': 0,
			'dont-craft-manually-achievement': 0,
			'dont-kill-manually-achievement': 0,
			'dont-research-before-researching-achievement': 0,
			'dont-use-entity-in-energy-production-achievement': 0,
			'equip-armor-achievement': 0,
			'group-attack-achievement': 0,
			'kill-achievement': 0,
			'module-transfer-achievement': 0,
			'place-equipment-achievement': 0,
			'player-damaged-achievement': 0,
			'produce-achievement': 0,
			'produce-per-hour-achievement': 0,
			'research-achievement': 0,
			'research-with-science-pack-achievement': 0,
			'shoot-achievement': 0,
			'space-connection-distance-traveled-achievement': 0,
			'train-path-achievement': 0,
			'use-entity-in-energy-production-achievement': 0,
			'use-item-achievement': 0,
		},
		'active-trigger': {
			'chain-active-trigger': 0,
			'delayed-active-trigger': 0,
		},
		'airborne-pollutant': { 'airborne-pollutant': 0 },
		'ambient-sound': { 'ambient-sound': 0 },
		'ammo-category': { 'ammo-category': 0 },
		animation: { animation: 0 },
		'asteroid-chunk': { 'asteroid-chunk': 0 },
		'autoplace-control': { 'autoplace-control': 0 },
		'burner-usage': { 'burner-usage': 0 },
		'collision-layer': { 'collision-layer': 0 },
		'custom-event': { 'custom-event': 0 },
		'custom-input': { 'custom-input': 0 },
		'damage-type': { 'damage-type': 0 },
		decorative: { 'optimized-decorative': 0 },
		'deliver-category': { 'deliver-category': 0 },
		'deliver-impact-combination': { 'deliver-impact-combination': 0 },
		'editor-controller': { 'editor-controller': 0 },
		entity: {
			accumulator: 0,
			'agricultural-tower': 0,
			'ammo-turret': 0,
			'arithmetic-combinator': 0,
			arrow: 0,
			'artillery-flare': 0,
			'artillery-projectile': 0,
			'artillery-turret': 0,
			'artillery-wagon': 0,
			'assembling-machine': 0,
			asteroid: 0,
			'asteroid-collector': 0,
			beacon: 0,
			beam: 0,
			boiler: 0,
			'burner-generator': 0,
			'capture-robot': 0,
			car: 0,
			'cargo-bay': 0,
			'cargo-landing-pad': 0,
			'cargo-pod': 0,
			'cargo-wagon': 0,
			character: 0,
			'character-corpse': 0,
			cliff: 0,
			'combat-robot': 0,
			'constant-combinator': 0,
			'construction-robot': 0,
			container: 0,
			corpse: 0,
			'curved-rail-a': 0,
			'curved-rail-b': 0,
			'decider-combinator': 0,
			'deconstructible-tile-proxy': 0,
			'display-panel': 0,
			'electric-energy-interface': 0,
			'electric-pole': 0,
			'electric-turret': 0,
			'elevated-curved-rail-a': 0,
			'elevated-curved-rail-b': 0,
			'elevated-half-diagonal-rail': 0,
			'elevated-straight-rail': 0,
			'entity-ghost': 0,
			explosion: 0,
			fire: 0,
			fish: 0,
			'fluid-turret': 0,
			'fluid-wagon': 0,
			furnace: 0,
			'fusion-generator': 0,
			'fusion-reactor': 0,
			gate: 0,
			generator: 0,
			'half-diagonal-rail': 0,
			'heat-interface': 0,
			'heat-pipe': 0,
			'highlight-box': 0,
			'infinity-container': 0,
			'infinity-pipe': 0,
			inserter: 0,
			'item-entity': 0,
			'item-request-proxy': 0,
			lab: 0,
			lamp: 0,
			'land-mine': 0,
			'lane-splitter': 0,
			'legacy-curved-rail': 0,
			'legacy-straight-rail': 0,
			lightning: 0,
			'lightning-attractor': 0,
			'linked-belt': 0,
			'linked-container': 0,
			loader: 0,
			'loader-1x1': 0,
			locomotive: 0,
			'logistic-container': 0,
			'logistic-robot': 0,
			market: 0,
			'mining-drill': 0,
			'offshore-pump': 0,
			'particle-source': 0,
			pipe: 0,
			'pipe-to-ground': 0,
			plant: 0,
			'player-port': 0,
			'power-switch': 0,
			'programmable-speaker': 0,
			projectile: 0,
			pump: 0,
			radar: 0,
			'rail-chain-signal': 0,
			'rail-ramp': 0,
			'rail-remnants': 0,
			'rail-signal': 0,
			'rail-support': 0,
			reactor: 0,
			resource: 0,
			roboport: 0,
			'rocket-silo': 0,
			'rocket-silo-rocket': 0,
			'rocket-silo-rocket-shadow': 0,
			segment: 0,
			'segmented-unit': 0,
			'selector-combinator': 0,
			'simple-entity': 0,
			'simple-entity-with-force': 0,
			'simple-entity-with-owner': 0,
			'smoke-with-trigger': 0,
			'solar-panel': 0,
			'space-platform-hub': 0,
			'speech-bubble': 0,
			'spider-leg': 0,
			'spider-unit': 0,
			'spider-vehicle': 0,
			splitter: 0,
			sticker: 0,
			'storage-tank': 0,
			'straight-rail': 0,
			stream: 0,
			'temporary-container': 0,
			thruster: 0,
			'tile-ghost': 0,
			'train-stop': 0,
			'transport-belt': 0,
			tree: 0,
			turret: 0,
			'underground-belt': 0,
			unit: 0,
			'unit-spawner': 0,
			wall: 0,
		},
		equipment: {
			'active-defense-equipment': 0,
			'battery-equipment': 0,
			'belt-immunity-equipment': 0,
			'energy-shield-equipment': 0,
			'equipment-ghost': 0,
			'generator-equipment': 0,
			'inventory-bonus-equipment': 0,
			'movement-bonus-equipment': 0,
			'night-vision-equipment': 0,
			'roboport-equipment': 0,
			'solar-panel-equipment': 0,
		},
		'equipment-category': { 'equipment-category': 0 },
		'equipment-grid': { 'equipment-grid': 0 },
		fluid: { fluid: 0 },
		font: { font: 0 },
		'fuel-category': { 'fuel-category': 0 },
		'god-controller': { 'god-controller': 0 },
		'gui-style': { 'gui-style': 0 },
		'impact-category': { 'impact-category': 0 },
		item: {
			ammo: 0,
			armor: 0,
			blueprint: 0,
			'blueprint-book': 0,
			capsule: 0,
			'copy-paste-tool': 0,
			'deconstruction-item': 0,
			gun: 0,
			item: 0,
			'item-with-entity-data': 0,
			'item-with-inventory': 0,
			'item-with-label': 0,
			'item-with-tags': 0,
			module: 0,
			'rail-planner': 0,
			'repair-tool': 0,
			'selection-tool': 0,
			'space-platform-starter-pack': 0,
			'spidertron-remote': 0,
			tool: 0,
			'upgrade-item': 0,
		},
		'item-group': { 'item-group': 0 },
		'item-subgroup': { 'item-subgroup': 0 },
		'map-gen-presets': { 'map-gen-presets': 0 },
		'map-settings': { 'map-settings': 0 },
		'module-category': { 'module-category': 0 },
		'mouse-cursor': { 'mouse-cursor': 0 },
		'noise-expression': { 'noise-expression': 0 },
		'noise-function': { 'noise-function': 0 },
		particle: { 'optimized-particle': 0 },
		procession: { procession: 0 },
		'procession-layer-inheritance-group': {
			'procession-layer-inheritance-group': 0,
		},
		quality: { quality: 0 },
		recipe: { recipe: 0 },
		'recipe-category': { 'recipe-category': 0 },
		'remote-controller': { 'remote-controller': 0 },
		'resource-category': { 'resource-category': 0 },
		shortcut: { shortcut: 0 },
		sound: { sound: 0 },
		'space-connection': { 'space-connection': 0 },
		'space-location': { planet: 0, 'space-location': 0 },
		'spectator-controller': { 'spectator-controller': 0 },
		sprite: { sprite: 0 },
		surface: { surface: 0 },
		'surface-property': { 'surface-property': 0 },
		technology: { technology: 0 },
		tile: { tile: 0 },
		'tile-effect': { 'tile-effect': 0 },
		'tips-and-tricks-item': { 'tips-and-tricks-item': 0 },
		'tips-and-tricks-item-category': { 'tips-and-tricks-item-category': 0 },
		'trigger-target-type': { 'trigger-target-type': 0 },
		'trivial-smoke': { 'trivial-smoke': 0 },
		tutorial: { tutorial: 0 },
		'utility-constants': { 'utility-constants': 0 },
		'utility-sounds': { 'utility-sounds': 0 },
		'utility-sprites': { 'utility-sprites': 0 },
		'virtual-signal': { 'virtual-signal': 0 },
	},
	rail_layer: { ground: 0, elevated: 1 },
	selection_mode: {
		select: 1,
		alt_select: 2,
		reverse_select: 4,
		alt_reverse_select: 5,
	},
	print_sound: { always: 1, never: 0, use_player_settings: 2 },
	print_skip: { never: 0, if_redundant: 1, if_visible: 2 },
	target_type: {
		entity: 1,
		equipment: 2,
		equipment_grid: 3,
		item: 4,
		logistic_cell: 5,
		logistic_network: 6,
		logistic_section: 7,
		permission_group: 8,
		planet: 9,
		player: 10,
		rail_path: 11,
		render_object: 12,
		space_platform: 13,
		surface: 14,
		train: 15,
		commandable: 16,
		custom_chart_tag: 17,
		gui_element: 18,
	},
	moving_state: { stale: 0, moving: 1, adaptive: 2, stuck: 3 },
	default_icon_size: 64,
	build_mode: { normal: 0, forced: 1, superforced: 2 },
	robot_order_type: {
		construct: 2,
		pickup: 0,
		deliver: 7,
		repair: 1,
		deconstruct: 3,
		deliver_items: 4,
		upgrade: 5,
		explode_cliff: 6,
		pickup_items: 8,
	},
	logistic_section_type: {
		manual: 0,
		circuit_controlled: 1,
		transitional_request_controlled: 2,
		request_missing_materials_controlled: 3,
	},
} as const;
